name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::016617991162:role/GitHubActionDeployToEC2
          aws-region: ap-south-1
      - name: Additional steps
        run: |
            # Your commands that require AWS credentials
            aws sts get-caller-identity

      - name: Deploy via SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --targets "Key=tag:Env,Values=Development"  \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy ${{ github.sha }}" \
            --parameters commands='[
              "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:'"${GITHUB_SHA}"'",
              "docker stop backend || true",
              "docker rm backend || true",
              "docker run -d --name backend -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/backend:'"${GITHUB_SHA}"'"
            ]' \
            
            --query "Command.CommandId" \
            --output text)
            echo "command_id=$COMMAND_ID" >> "$GITHUB_OUTPUT"
            echo "Sent command: $COMMAND_ID"

            sleep 5

            aws ssm list-commands \
            --command-id "$COMMAND_ID" \
            --query "Commands[0].[CommandId,Status,TargetCount,CompletedCount,ErrorCount]" \
            --output table
